[dotfiles]
"~/.zshrc" = { source = "~/dotfiles/zsh/zshrc" }
"~/.zshenv" = { source = "~/dotfiles/zsh/zshenv" }
"~/.gitconfig" = { source = "~/dotfiles/git/gitconfig" }
"~/.gitignore_global" = { source = "~/dotfiles/git/gitignore" }
"~/.editorconfig" = { source = "~/dotfiles/neovim/.editorconfig" }
"~/.perlcriticrc" = { source = "~/dotfiles/.perlcriticrc" }
"~/.perltidyrc" = { source = "~/dotfiles/.perltidyrc" }
"~/.config/starship.toml" = { source = "~/dotfiles/zsh/starship.toml" }
"~/.config/hunk/config.toml" = { source = "~/dotfiles/git/hunk.toml" }
# "~/.config/zellij" = { source = "~/dotfiles/zellij" }
# "~/.config/herdr" = { source = "~/dotfiles/herdr" }  # herdr 停止中
"~/.config/nvim/init.lua" = { source = "~/dotfiles/neovim/init.lua" }
"~/.config/nvim/lua" = { source = "~/dotfiles/neovim/lua" }
"~/.config/nvim/coc-settings.json" = { source = "~/dotfiles/neovim/coc-settings.json" }
"~/.config/nvim/lazy-lock.json" = { source = "~/dotfiles/neovim/lazy-lock.json" }
"~/.tmux.conf" = { source = "~/dotfiles/tmux/tmux.conf.tmpl", mode = "template" }
"~/.local/share/sheldon/plugins.lock" = { source = "~/dotfiles/zsh/sheldon/plugins.lock" }
