# easy aline
[[plugins]]
repo = 'junegunn/vim-easy-align'

# markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'

# ctrl+p でファイルあいまい検索ができる
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

# neosinppet for vim

##入力補完ctrl + k で次の入力するところに飛べる
[[plugins]]
repo = 'Shougo/neocomplcache'
if = '!has("nvim")'

## スニペットの補完機能
[[plugins]]
repo = 'Shougo/neosnippet'
if = '!has("nvim")'

## スニペット集
[[plugins]]
repo = 'Shougo/neosnippet-snippets'
if = '!has("nvim")'

# copilot for nvim
[[plugins]]
repo = 'github/copilot.vim'
if = 'has("nvim")'
hook_source = '''
let g:copilot_no_maps = v:true
imap <script><silent><nowait><expr> <C-g> copilot#Accept()
'''

# fで検索後移動できるようにする
[[plugins]]
repo = 'rhysd/clever-f.vim'

# 気分によってcolorschemeかえる
[[plugins]]
repo = 'flazz/vim-colorschemes'

#:Gdiffと打つとHEADと現在の状態を比較できる
#:Glog = git log
#:Gdiff コミット番号でそのdiffをとれる
#:Gblameでコミット詳細みれる
#:Gstatus = git status
#:Gwrite [path]
#:Gcommit
#:Gdiff [fugitive-revision]
#:Gedit [fugitive-revision]
#:Gmove [destination]
#:Gremove
#:Glog [args]
#:Gpush [args]
#:Gfetch [args]
#:Gmerge [args]
#:Gpull [args]
[[plugins]]
repo = 'tpope/vim-fugitive'
