require("base")
require("env")
require("lazy-ready")
require("setup")
-- require("setup2")
-- require("setup3")
-- require("lazy-test")
require("switch-indent")
require("switch-gutter")
require("override")
