require("base")
require("env")
require("lazy-ready")
require("setup")
-- require("setup2")
-- require("setup3")
--  require("lazy-test")
require("switch-indent")
require("switch-gutter")
require("override")
-- 例: 「=」キーに対する動作を設定
--local smartchr2 = require("smartchr2")
--smartchr2.map("=", { "=", " = ", "=>" })
--smartchr2.map("-", { "-", " -> ", "-->" }, { loop = true })
